# Summary

Linear regression was run to find point estimates for predicting incident_rate. Because of multiple missing values, the model was first run on a subset of data (where Year=2021) which had fewer missing values that were missing at random asides from the Refugees column which had multiple values that were missing not at random. MICE imputations was hence used to replace the values. However, the particular column that had most of the missing values was dropped as it didn't belong to the model, therefore, Linear regression model was run without using the MICE imputations. This final model returned the following point estimates:

Crime_Rate = -372.23 + 0.0003Average_total_income + 44.49Low_income_rate + 3.56Non_immigrants + 3.48Non_citizen.


For the total dataset, the Refugees column was dropped too as it had multiple values that were missing not at random. The Low_income_rate column also had a higher amount of missing values, however, the missing values were replaced using MICE imputations. The model was run and these were observed:

- The Low_income_rate p-value: 0.64, is higher than alpha:0.05. However, this independent variable was left in the final model because this maybe due to MICE imputations as it had large volume of missing values in the total dataset. Unlike in the 2021 dataset where there was no missing value in the Low_income_rate column, and this subset dataset showed a near zero p-value for Low_income_rate.

- The p-value of Postsecondary_Graduate tend to increase when Non_citizen and Non_immigrants variable are removed, suggesting a multicollinearity problem. However, hypothesis testing could not be done on MICE result.

- Population has a zero (0) coefficient in the final model which is the same in the subset model. Although in the subset model,population had a higher p-value than alpha(0.05), hence was no included in the final model. 

The final model returned the following point estimates:

Crime_Rate = 10.8035 + 0*Population + 1.1Low_income_rate + 0.2*Visible_Minority + (-0.09)*Owner + (-0.1)*Renter

In [1]:
#Import the required libraries
import pandas as pd
import os.path as osp

#Build the path for the data file
data_path = osp.join(
    osp.curdir,'Data','C:/Users/3939/Documents/MMA Courses/MMA 860/Renamed_Excel_Data.xlsx')

#Use the read_excel function to pull data from the 'Bees' sheet
Project1 = pd.read_excel(
    data_path,'used_data',index_col='Assigned number')
Project1.head()

,Regions,No_of_Incidents,Population,Crime_rate,Population_percentage_change,Unemployment_rate,Average_total_income,Average_value_of_dwellings,Low_income_rate,Postsecondary_Graduate,Married_or_Common_law,Non_immigrants,Non_citizen,Refugees,Visible_Minority,Owner,Renter,Year
Assigned number,,,,,,,,,,,,,,,,,,
1,"Amherst, Town (T)",220,9413,2.337193,-3.10,11.60,34514.0,136236,-,36.86,43.98,94.6,2.44,28.57,4.1,59.66,40.34,2016
2,"Annapolis, All SubdivisionsAnnapolis, All Subd...",461,18252,2.525751,-1.03,12.48,32384.0,177993.75,0.01,42.33,56.11,92.87,5.49,2.38,1.6,85.04,14.87,2016
3,"Annapolis Royal, Town (T)",17,491,3.462322,2.10,9.40,39372.0,263604,0.05,58.04,47.86,76.37,22.4,-,3.09,49.15,50.85,2016
4,"Antigonish, All Subdivisions",239,14584,1.638782,-0.90,11.95,43330.0,201412,-,50.37,52.14,95.7,4.08,2.27,3.05,86.51,13.49,2016
5,"Antigonish, Town (T)",179,4364,4.101742,-3.50,9.70,39414.0,236826,-,49.04,37.58,85.01,9.05,-,9.63,46.50,53.50,2016

In [2]:
Project1.describe()

,No_of_Incidents,Population,Crime_rate,Population_percentage_change,Unemployment_rate,Average_total_income,Postsecondary_Graduate,Married_or_Common_law,Owner,Renter,Year
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.0000,60.000000,60.000000
mean,528.833333,28427.133333,3.213065,2.794333,14.026000,39129.197333,45.729833,50.859167,66.0995,26.660833,2018.500000
std,1113.602372,75907.154908,2.294971,19.916060,4.418709,6131.961741,8.102492,9.266857,21.0098,14.621746,2.521097
min,10.000000,491.000000,1.207079,-6.500000,7.300000,18275.000000,24.250000,19.740000,9.4600,3.000000,2016.000000
25%,150.500000,4529.750000,1.910093,-3.100000,11.250000,36477.250000,40.977500,47.127500,57.1150,14.300000,2016.000000
50%,230.000000,9205.000000,2.385926,0.465000,12.840000,39393.000000,44.750000,52.070000,68.9050,22.895000,2018.500000
75%,477.250000,18397.500000,3.328390,3.185000,17.227500,43285.000000,50.700000,56.925000,83.8075,39.980000,2021.000000
max,6415.000000,439819.000000,11.943540,151.500000,28.650000,52900.000000,62.600000,63.700000,89.2500,57.500000,2021.000000

In [3]:
Project1.dtypes

Regions                          object
No_of_Incidents                   int64
Population                        int64
Crime_rate                      float64
Population_percentage_change    float64
Unemployment_rate               float64
Average_total_income            float64
Average_value_of_dwellings       object
Low_income_rate                  object
Postsecondary_Graduate          float64
Married_or_Common_law           float64
Non_immigrants                   object
Non_citizen                      object
Refugees                         object
Visible_Minority                 object
Owner                           float64
Renter                          float64
Year                              int64
dtype: object

In [4]:
Project1.corr()

C:\Users\3939\AppData\Local\Temp\ipykernel_19544\3305109309.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  Project1.corr()

,No_of_Incidents,Population,Crime_rate,Population_percentage_change,Unemployment_rate,Average_total_income,Postsecondary_Graduate,Married_or_Common_law,Owner,Renter,Year
No_of_Incidents,1.000000,0.992209,-0.195669,0.005366,-0.203577,0.333681,0.258748,0.058627,-0.007109,0.160714,-0.003532
Population,0.992209,1.000000,-0.224487,0.007548,-0.194584,0.352056,0.283124,0.065849,-0.002801,0.172493,0.007189
Crime_rate,-0.195669,-0.224487,1.000000,0.138824,0.286079,-0.559709,-0.439088,-0.633630,-0.684040,-0.215381,0.028333
Population_percentage_change,0.005366,0.007548,0.138824,1.000000,-0.007233,0.056340,0.107154,-0.030720,-0.133229,-0.118518,0.229256
Unemployment_rate,-0.203577,-0.194584,0.286079,-0.007233,1.000000,-0.350258,-0.282356,-0.237678,-0.094661,-0.334631,0.142790
Average_total_income,0.333681,0.352056,-0.559709,0.056340,-0.350258,1.000000,0.765194,0.652225,0.445234,0.255321,0.482528
Postsecondary_Graduate,0.258748,0.283124,-0.439088,0.107154,-0.282356,0.765194,1.000000,0.470467,0.229162,0.348903,0.504956
Married_or_Common_law,0.058627,0.065849,-0.633630,-0.030720,-0.237678,0.652225,0.470467,1.000000,0.863103,-0.219437,0.385321
Owner,-0.007109,-0.002801,-0.684040,-0.133229,-0.094661,0.445234,0.229162,0.863103,1.000000,-0.321967,0.003512
Renter,0.160714,0.172493,-0.215381,-0.118518,-0.334631,0.255321,0.348903,-0.219437,-0.321967,1.000000,-0.009345
Year,-0.003532,0.007189,0.028333,0.229256,0.142790,0.482528,0.504956,0.385321,0.003512,-0.009345,1.000000

In [5]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [6]:
Project1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60 entries, 1 to 30
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Regions                       60 non-null     object
 1   No_of_Incidents               60 non-null     int64
 2   Population                    60 non-null     int64
 3   Crime_rate                    60 non-null     float64
 4   Population_percentage_change  60 non-null     float64
 5   Unemployment_rate             60 non-null     float64
 6   Average_total_income          60 non-null     float64
 7   Average_value_of_dwellings    57 non-null     object
 8   Low_income_rate               60 non-null     object
 9   Postsecondary_Graduate        60 non-null     float64
 10  Married_or_Common_law         60 non-null     float64
 11  Non_immigrants                58 non-null     object
 12  Non_citizen                   60 non-null     object
 13  Refugees                      58 non-null     object
 14  Visible_Minority              60 non-null     object
 15  Owner                         60 non-null     float64
 16  Renter                        60 non-null     float64
 17  Year                          60 non-null     int64
dtypes: float64(8), int64(3), object(7)
memory usage: 8.9+ KB

In [7]:
#Convert object datatypes to numeric(int or float as the case maybe)

Project1['Non_citizen'] = pd.to_numeric(Project1['Non_citizen'], errors='coerce')

In [8]:
Project1['Average_value_of_dwellings'] = pd.to_numeric(Project1['Average_value_of_dwellings'], errors='coerce')

In [9]:
Project1['Low_income_rate'] = pd.to_numeric(Project1['Low_income_rate'], errors='coerce')

In [10]:
Project1['Non_immigrants'] = pd.to_numeric(Project1['Non_immigrants'], errors='coerce')

In [11]:
Project1['Refugees'] = pd.to_numeric(Project1['Refugees'], errors='coerce')

In [12]:
Project1['Visible_Minority'] = pd.to_numeric(Project1['Visible_Minority'], errors='coerce')

In [13]:
Project1.head()

,Regions,No_of_Incidents,Population,Crime_rate,Population_percentage_change,Unemployment_rate,Average_total_income,Average_value_of_dwellings,Low_income_rate,Postsecondary_Graduate,Married_or_Common_law,Non_immigrants,Non_citizen,Refugees,Visible_Minority,Owner,Renter,Year
Assigned number,,,,,,,,,,,,,,,,,,
1,"Amherst, Town (T)",220,9413,2.337193,-3.10,11.60,34514.0,136236.00,NaN,36.86,43.98,94.60,2.44,28.57,4.10,59.66,40.34,2016
2,"Annapolis, All SubdivisionsAnnapolis, All Subd...",461,18252,2.525751,-1.03,12.48,32384.0,177993.75,0.01,42.33,56.11,92.87,5.49,2.38,1.60,85.04,14.87,2016
3,"Annapolis Royal, Town (T)",17,491,3.462322,2.10,9.40,39372.0,263604.00,0.05,58.04,47.86,76.37,22.40,NaN,3.09,49.15,50.85,2016
4,"Antigonish, All Subdivisions",239,14584,1.638782,-0.90,11.95,43330.0,201412.00,NaN,50.37,52.14,95.70,4.08,2.27,3.05,86.51,13.49,2016
5,"Antigonish, Town (T)",179,4364,4.101742,-3.50,9.70,39414.0,236826.00,NaN,49.04,37.58,85.01,9.05,NaN,9.63,46.50,53.50,2016

In [14]:
Project1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60 entries, 1 to 30
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Regions                       60 non-null     object
 1   No_of_Incidents               60 non-null     int64
 2   Population                    60 non-null     int64
 3   Crime_rate                    60 non-null     float64
 4   Population_percentage_change  60 non-null     float64
 5   Unemployment_rate             60 non-null     float64
 6   Average_total_income          60 non-null     float64
 7   Average_value_of_dwellings    54 non-null     float64
 8   Low_income_rate               37 non-null     float64
 9   Postsecondary_Graduate        60 non-null     float64
 10  Married_or_Common_law         60 non-null     float64
 11  Non_immigrants                55 non-null     float64
 12  Non_citizen                   55 non-null     float64
 13  Refugees                      32 non-null     float64
 14  Visible_Minority              58 non-null     float64
 15  Owner                         60 non-null     float64
 16  Renter                        60 non-null     float64
 17  Year                          60 non-null     int64
dtypes: float64(14), int64(3), object(1)
memory usage: 8.9+ KB

In [15]:
Project1.isnull().sum().sum()

69

No of missing values is higher than the sample size of 60. Since majority of the missing data is in 2016. I will run the linear regression on 2021 alone first.

In [16]:
#Creating a new dataset with 2021 as the only year

import pandasql
new_Project1 = pandasql.sqldf("SELECT * FROM Project1 WHERE Year=2021 GROUP BY Regions;")

new_Project1.head()

,Assigned number,Regions,No_of_Incidents,Population,Crime_rate,Population_percentage_change,Unemployment_rate,Average_total_income,Average_value_of_dwellings,Low_income_rate,Postsecondary_Graduate,Married_or_Common_law,Non_immigrants,Non_citizen,Refugees,Visible_Minority,Owner,Renter,Year
0,1,"Amherst, Town (T)",286,9404,3.041259,-0.1,11.90,40640.0,160800.0,0.22,44.20,50.20,96.10,3.90,NaN,5.00,57.30,42.70,2021
1,3,"Annapolis Royal, Town (T)",10,530,1.886792,7.9,13.20,42400.0,288000.0,0.26,59.80,51.00,84.80,14.10,NaN,3.00,56.30,45.30,2021
2,2,"Annapolis, All SubdivisionsAnnapolis, All Subd...",393,18834,2.086652,3.1,12.25,38000.0,231450.0,0.21,49.95,62.90,93.05,6.78,1.7,2.35,83.43,16.63,2021
3,4,"Antigonish, All Subdivisions",218,15101,1.443613,2.8,11.00,47985.0,249800.0,0.12,60.15,61.75,95.25,4.80,NaN,4.75,86.20,13.80,2021
4,5,"Antigonish, Town (T)",200,4656,4.295533,6.7,17.60,42360.0,252800.0,0.21,59.30,41.80,87.70,12.20,17.8,12.90,43.30,56.70,2021

In [17]:
#Set Assigned number column as index

new_Project1.set_index('Assigned number', inplace=True)

new_Project1.head()

,Regions,No_of_Incidents,Population,Crime_rate,Population_percentage_change,Unemployment_rate,Average_total_income,Average_value_of_dwellings,Low_income_rate,Postsecondary_Graduate,Married_or_Common_law,Non_immigrants,Non_citizen,Refugees,Visible_Minority,Owner,Renter,Year
Assigned number,,,,,,,,,,,,,,,,,,
1,"Amherst, Town (T)",286,9404,3.041259,-0.1,11.90,40640.0,160800.0,0.22,44.20,50.20,96.10,3.90,NaN,5.00,57.30,42.70,2021
3,"Annapolis Royal, Town (T)",10,530,1.886792,7.9,13.20,42400.0,288000.0,0.26,59.80,51.00,84.80,14.10,NaN,3.00,56.30,45.30,2021
2,"Annapolis, All SubdivisionsAnnapolis, All Subd...",393,18834,2.086652,3.1,12.25,38000.0,231450.0,0.21,49.95,62.90,93.05,6.78,1.7,2.35,83.43,16.63,2021
4,"Antigonish, All Subdivisions",218,15101,1.443613,2.8,11.00,47985.0,249800.0,0.12,60.15,61.75,95.25,4.80,NaN,4.75,86.20,13.80,2021
5,"Antigonish, Town (T)",200,4656,4.295533,6.7,17.60,42360.0,252800.0,0.21,59.30,41.80,87.70,12.20,17.8,12.90,43.30,56.70,2021

In [18]:
new_Project1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30 entries, 1 to 30
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Regions                       30 non-null     object
 1   No_of_Incidents               30 non-null     int64
 2   Population                    30 non-null     int64
 3   Crime_rate                    30 non-null     float64
 4   Population_percentage_change  30 non-null     float64
 5   Unemployment_rate             30 non-null     float64
 6   Average_total_income          30 non-null     float64
 7   Average_value_of_dwellings    27 non-null     float64
 8   Low_income_rate               30 non-null     float64
 9   Postsecondary_Graduate        30 non-null     float64
 10  Married_or_Common_law         30 non-null     float64
 11  Non_immigrants                28 non-null     float64
 12  Non_citizen                   28 non-null     float64
 13  Refugees                      15 non-null     float64
 14  Visible_Minority              30 non-null     float64
 15  Owner                         30 non-null     float64
 16  Renter                        30 non-null     float64
 17  Year                          30 non-null     int64
dtypes: float64(14), int64(3), object(1)
memory usage: 4.5+ KB

In [19]:
#Removing non-numeric column:Regions, as it may affect MICE imputation

new_Project1= new_Project1.drop('Regions',axis=1)

new_Project1.head()

,No_of_Incidents,Population,Crime_rate,Population_percentage_change,Unemployment_rate,Average_total_income,Average_value_of_dwellings,Low_income_rate,Postsecondary_Graduate,Married_or_Common_law,Non_immigrants,Non_citizen,Refugees,Visible_Minority,Owner,Renter,Year
Assigned number,,,,,,,,,,,,,,,,,
1,286,9404,3.041259,-0.1,11.90,40640.0,160800.0,0.22,44.20,50.20,96.10,3.90,NaN,5.00,57.30,42.70,2021
3,10,530,1.886792,7.9,13.20,42400.0,288000.0,0.26,59.80,51.00,84.80,14.10,NaN,3.00,56.30,45.30,2021
2,393,18834,2.086652,3.1,12.25,38000.0,231450.0,0.21,49.95,62.90,93.05,6.78,1.7,2.35,83.43,16.63,2021
4,218,15101,1.443613,2.8,11.00,47985.0,249800.0,0.12,60.15,61.75,95.25,4.80,NaN,4.75,86.20,13.80,2021
5,200,4656,4.295533,6.7,17.60,42360.0,252800.0,0.21,59.30,41.80,87.70,12.20,17.8,12.90,43.30,56.70,2021

In [20]:
new_Project1.isnull().sum().sum()

22

In [21]:
#Removed the Refugees column as I ran into an error.
#The error message indicates that the Singular Value Decomposition (SVD) did not converge, 
#which typically happens when the algorithm fails to find a satisfactory solution.
#The Refugees column was removed since it has 15 missing values,
#and these were not missing at random.

new_Project2= new_Project1.drop('Refugees',axis=1)

new_Project2.head()

,No_of_Incidents,Population,Crime_rate,Population_percentage_change,Unemployment_rate,Average_total_income,Average_value_of_dwellings,Low_income_rate,Postsecondary_Graduate,Married_or_Common_law,Non_immigrants,Non_citizen,Visible_Minority,Owner,Renter,Year
Assigned number,,,,,,,,,,,,,,,,
1,286,9404,3.041259,-0.1,11.90,40640.0,160800.0,0.22,44.20,50.20,96.10,3.90,5.00,57.30,42.70,2021
3,10,530,1.886792,7.9,13.20,42400.0,288000.0,0.26,59.80,51.00,84.80,14.10,3.00,56.30,45.30,2021
2,393,18834,2.086652,3.1,12.25,38000.0,231450.0,0.21,49.95,62.90,93.05,6.78,2.35,83.43,16.63,2021
4,218,15101,1.443613,2.8,11.00,47985.0,249800.0,0.12,60.15,61.75,95.25,4.80,4.75,86.20,13.80,2021
5,200,4656,4.295533,6.7,17.60,42360.0,252800.0,0.21,59.30,41.80,87.70,12.20,12.90,43.30,56.70,2021

In [22]:
new_Project2.isnull().sum().sum()

7

In [25]:
frmla = 'Crime_rate ~ Population + Population_percentage_change + Unemployment_rate + Average_total_income + ' + \
'Average_value_of_dwellings + Low_income_rate + Postsecondary_Graduate + Married_or_Common_law + Non_immigrants + ' + \
'Non_citizen + Visible_Minority + Owner + Renter + Year'

In [26]:
#Running a linear regression model

model = ols(frmla,new_Project2).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             Crime_rate   R-squared:                       0.685
Model:                            OLS   Adj. R-squared:                  0.369
Method:                 Least Squares   F-statistic:                     2.172
Date:                Fri, 12 Apr 2024   Prob (F-statistic):             0.0877
Time:                        09:30:02   Log-Likelihood:                -30.923
No. Observations:                  27   AIC:                             89.85
Df Residuals:                      13   BIC:                             108.0
Df Model:                          13
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                    -8.839e-05   4.11e-05     -2.153      0.051      -0.000    3.12e-07
Population                   -8.653e-06   5.15e-06     -1.679      0.117   -1.98e-05    2.48e-06
Population_percentage_change    -0.1748      0.136     -1.290      0.220      -0.468       0.118
Unemployment_rate                0.0663      0.129      0.513      0.616      -0.213       0.346
Average_total_income             0.0004      0.000      2.030      0.063   -2.36e-05       0.001
Average_value_of_dwellings    5.773e-06   2.13e-05      0.271      0.791   -4.03e-05    5.19e-05
Low_income_rate                 41.3687     13.368      3.095      0.009      12.489      70.249
Postsecondary_Graduate          -0.0466      0.071     -0.658      0.522      -0.200       0.106
Married_or_Common_law            0.0454      0.234      0.194      0.849      -0.459       0.550
Non_immigrants                   3.4145      1.692      2.018      0.065      -0.241       7.071
Non_citizen                      3.5093      1.880      1.866      0.085      -0.553       7.571
Visible_Minority                 0.0783      0.140      0.560      0.585      -0.224       0.380
Owner                           -0.0387      0.065     -0.596      0.561      -0.179       0.101
Renter                          -0.0323      0.078     -0.415      0.685      -0.201       0.136
Year                            -0.1786      0.083     -2.153      0.051      -0.358       0.001
==============================================================================
Omnibus:                        0.688   Durbin-Watson:                   2.397
Prob(Omnibus):                  0.709   Jarque-Bera (JB):                0.679
Skew:                          -0.050   Prob(JB):                        0.712
Kurtosis:                       2.230   Cond. No.                     2.31e+22
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.96e-33. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [28]:
#Import the required libraries

import statsmodels.imputation.mice as mice
import statsmodels.regression.linear_model as sm


#Impute the data set with MICE Data

imp = mice.MICEData(new_Project2)
imputed_data = imp.next_sample()

In [29]:
#n_imputations=5 as less than 5% of data is missing

mice = mice.MICE(frmla, sm.OLS, imp)
results = mice.fit(n_imputations=5)
print(results.summary())

                                   Results: MICE
===================================================================================
Method:                        MICE                 Sample size:               30
Model:                         OLS                  Scale                      1.43
Dependent variable:            Crime_rate           Num. imputations           5
-----------------------------------------------------------------------------------
                              Coef.  Std.Err.    t    P>|t|   [0.025  0.975]  FMI
-----------------------------------------------------------------------------------
Intercept                    -0.0001   0.0000 -1.5294 0.1262 -0.0002  0.0000 0.5547
Population                   -0.0000   0.0000 -1.1882 0.2347 -0.0000  0.0000 0.0430
Population_percentage_change -0.0010   0.0155 -0.0650 0.9482 -0.0313  0.0293 0.5482
Unemployment_rate             0.0567   0.1173  0.4832 0.6290 -0.1732  0.2866 0.1789
Average_total_income          0.0003   0.0002  1.6158 0.1061 -0.0001  0.0007 0.0660
Average_value_of_dwellings    0.0000   0.0000  0.3844 0.7007 -0.0000  0.0001 0.3484
Low_income_rate              45.1113  13.8968  3.2462 0.0012 17.8742 72.3485 0.1185
Postsecondary_Graduate       -0.0065   0.0785 -0.0830 0.9339 -0.1604  0.1474 0.1698
Married_or_Common_law         0.0609   0.2157  0.2821 0.7779 -0.3619  0.4837 0.5233
Non_immigrants                2.8212   1.9362  1.4571 0.1451 -0.9737  6.6162 0.5632
Non_citizen                   2.6167   2.0659  1.2666 0.2053 -1.4323  6.6658 0.4967
Visible_Minority              0.0877   0.1561  0.5618 0.5743 -0.2182  0.3936 0.2181
Owner                        -0.0378   0.0728 -0.5185 0.6041 -0.1805  0.1050 0.4876
Renter                       -0.0167   0.0642 -0.2600 0.7949 -0.1424  0.1091 0.5274
Year                         -0.1497   0.0979 -1.5294 0.1262 -0.3415  0.0421 0.5547
===================================================================================

In [30]:
new_Project2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30 entries, 1 to 30
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   No_of_Incidents               30 non-null     int64
 1   Population                    30 non-null     int64
 2   Crime_rate                    30 non-null     float64
 3   Population_percentage_change  30 non-null     float64
 4   Unemployment_rate             30 non-null     float64
 5   Average_total_income          30 non-null     float64
 6   Average_value_of_dwellings    27 non-null     float64
 7   Low_income_rate               30 non-null     float64
 8   Postsecondary_Graduate        30 non-null     float64
 9   Married_or_Common_law         30 non-null     float64
 10  Non_immigrants                28 non-null     float64
 11  Non_citizen                   28 non-null     float64
 12  Visible_Minority              30 non-null     float64
 13  Owner                         30 non-null     float64
 14  Renter                        30 non-null     float64
 15  Year                          30 non-null     int64
dtypes: float64(13), int64(3)
memory usage: 4.0 KB

Since Average_value_of_dwellings does not belong to the model and has 3 of the 7 missing values, the missing values is now reduced to 4 with a percentage of 0.13% which is near zero. Therefore, these missing values may not have much impact, hence the model can be run without MICE imputation.

In [31]:
frmla1 = 'Crime_rate ~ Population + Unemployment_rate + Average_total_income + ' + \
'Low_income_rate + Married_or_Common_law + Non_immigrants + ' + \
'Non_citizen + Visible_Minority + Owner + Renter'

model1 = ols(frmla1,new_Project2).fit()
model1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             Crime_rate   R-squared:                       0.655
Model:                            OLS   Adj. R-squared:                  0.453
Method:                 Least Squares   F-statistic:                     3.232
Date:                Fri, 12 Apr 2024   Prob (F-statistic):             0.0162
Time:                        09:31:53   Log-Likelihood:                -34.380
No. Observations:                  28   AIC:                             90.76
Df Residuals:                      17   BIC:                             105.4
Df Model:                          10
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept              -400.3570    147.715     -2.710      0.015    -712.008     -88.706
Population            -5.269e-06   4.32e-06     -1.220      0.239   -1.44e-05    3.84e-06
Unemployment_rate         0.0456      0.094      0.484      0.634      -0.153       0.244
Average_total_income      0.0003      0.000      2.310      0.034    2.94e-05       0.001
Low_income_rate          46.6952     11.695      3.993      0.001      22.022      71.369
Married_or_Common_law     0.0577      0.122      0.473      0.642      -0.200       0.316
Non_immigrants            3.7880      1.470      2.578      0.020       0.688       6.888
Non_citizen               3.7423      1.559      2.400      0.028       0.452       7.032
Visible_Minority          0.0396      0.128      0.309      0.761      -0.231       0.311
Owner                    -0.0263      0.042     -0.634      0.535      -0.114       0.061
Renter                   -0.0147      0.037     -0.397      0.696      -0.093       0.064
==============================================================================
Omnibus:                        1.508   Durbin-Watson:                   2.231
Prob(Omnibus):                  0.470   Jarque-Bera (JB):                1.307
Skew:                           0.496   Prob(JB):                        0.520
Kurtosis:                       2.631   Cond. No.                     6.54e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.54e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [32]:
#Remove variables that don't belong to the model and re-run

frmla2 = 'Crime_rate ~ Population + Average_total_income + Low_income_rate + ' + \
'Non_immigrants + Non_citizen + Owner + Renter'

model2 = ols(frmla2,new_Project2).fit()
model2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             Crime_rate   R-squared:                       0.649
Model:                            OLS   Adj. R-squared:                  0.526
Method:                 Least Squares   F-statistic:                     5.275
Date:                Fri, 12 Apr 2024   Prob (F-statistic):            0.00156
Time:                        09:31:57   Log-Likelihood:                -34.647
No. Observations:                  28   AIC:                             85.29
Df Residuals:                      20   BIC:                             95.95
Df Model:                           7
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept             -431.1198    123.812     -3.482      0.002    -689.388    -172.852
Population           -4.393e-06   3.44e-06     -1.278      0.216   -1.16e-05    2.78e-06
Average_total_income     0.0003      0.000      2.517      0.020    5.35e-05       0.001
Low_income_rate         45.6005     10.553      4.321      0.000      23.587      67.614
Non_immigrants           4.1385      1.209      3.422      0.003       1.616       6.661
Non_citizen              4.1328      1.273      3.248      0.004       1.478       6.787
Owner                   -0.0118      0.024     -0.488      0.631      -0.062       0.039
Renter                  -0.0179      0.027     -0.658      0.518      -0.075       0.039
==============================================================================
Omnibus:                        2.076   Durbin-Watson:                   2.291
Prob(Omnibus):                  0.354   Jarque-Bera (JB):                1.687
Skew:                           0.586   Prob(JB):                        0.430
Kurtosis:                       2.729   Cond. No.                     5.89e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.89e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [33]:
#Remove variables that don't belong to the model and re-run
frmla3 = 'Crime_rate ~ Average_total_income + Low_income_rate + ' + \
'Non_immigrants + Non_citizen'

model3 = ols(frmla3,new_Project2).fit()
model3.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             Crime_rate   R-squared:                       0.617
Model:                            OLS   Adj. R-squared:                  0.550
Method:                 Least Squares   F-statistic:                     9.256
Date:                Fri, 12 Apr 2024   Prob (F-statistic):           0.000131
Time:                        09:32:01   Log-Likelihood:                -35.862
No. Observations:                  28   AIC:                             81.72
Df Residuals:                      23   BIC:                             88.38
Df Model:                           4
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept             -372.2294    104.030     -3.578      0.002    -587.432    -157.026
Average_total_income     0.0003      0.000      2.431      0.023    3.94e-05       0.000
Low_income_rate         44.4927      8.996      4.946      0.000      25.883      63.102
Non_immigrants           3.5617      1.025      3.475      0.002       1.441       5.682
Non_citizen              3.4798      1.051      3.309      0.003       1.305       5.655
==============================================================================
Omnibus:                        1.209   Durbin-Watson:                   1.987
Prob(Omnibus):                  0.546   Jarque-Bera (JB):                1.141
Skew:                           0.365   Prob(JB):                        0.565
Kurtosis:                       2.333   Cond. No.                     2.45e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.45e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# This is the Final model for data subset (where Year = 2021).
Crime_Rate = -372.23 + 0.0003*Average_total_income + 44.49*Low_income_rate + 3.56*Non_immigrants + 3.48*Non_citizen

In [34]:
#Running a linear regression model

model5 = ols('Crime_rate ~ No_of_Incidents + Population + Population_percentage_change + ' + \
            'Unemployment_rate + Average_total_income + Average_value_of_dwellings + ' + \
            'Low_income_rate + Postsecondary_Graduate + Married_or_Common_law + ' + \
            'Non_immigrants + Non_citizen + Refugees + Visible_Minority + Owner + Renter + Year',Project1).fit()
print(model5.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             Crime_rate   R-squared:                       0.996
Model:                            OLS   Adj. R-squared:                  0.931
Method:                 Least Squares   F-statistic:                     15.24
Date:                Fri, 12 Apr 2024   Prob (F-statistic):              0.199
Time:                        09:32:05   Log-Likelihood:                 18.230
No. Observations:                  18   AIC:                            -2.459
Df Residuals:                       1   BIC:                             12.68
Df Model:                          16
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                     -213.8721   1990.133     -0.107      0.932   -2.55e+04    2.51e+04
No_of_Incidents                  0.0041      0.002      2.545      0.238      -0.017       0.025
Population                   -6.558e-05   2.15e-05     -3.047      0.202      -0.000       0.000
Population_percentage_change     0.0536      0.130      0.412      0.751      -1.601       1.708
Unemployment_rate               -0.0832      0.148     -0.562      0.674      -1.965       1.799
Average_total_income           -3.6e-06      0.000     -0.028      0.982      -0.002       0.002
Average_value_of_dwellings   -2.621e-07   1.46e-05     -0.018      0.989      -0.000       0.000
Low_income_rate                 -0.0193     14.457     -0.001      0.999    -183.710     183.672
Postsecondary_Graduate          -0.0356      0.108     -0.330      0.797      -1.408       1.337
Married_or_Common_law           -0.1813      0.195     -0.932      0.523      -2.654       2.291
Non_immigrants                   0.2522      0.694      0.363      0.778      -8.568       9.073
Non_citizen                      0.3592      0.731      0.492      0.709      -8.923       9.641
Refugees                         0.0547      0.045      1.214      0.439      -0.518       0.628
Visible_Minority                 0.2656      0.241      1.101      0.469      -2.800       3.331
Owner                            0.0358      0.060      0.600      0.656      -0.724       0.795
Renter                          -0.0972      0.041     -2.349      0.256      -0.623       0.429
Year                             0.0998      1.021      0.098      0.938     -12.869      13.068
==============================================================================
Omnibus:                        5.610   Durbin-Watson:                   1.651
Prob(Omnibus):                  0.061   Jarque-Bera (JB):                3.121
Skew:                          -0.925   Prob(JB):                        0.210
Kurtosis:                       3.862   Cond. No.                     5.68e+09
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.68e+09. This might indicate that there are
strong multicollinearity or other numerical problems.

C:\Users\3939\anaconda3\lib\site-packages\scipy\stats\_stats_py.py:1736: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=18
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

The F-test shows that this model has no predictive power, and the p-values are showing that no independent variable belong to the model. Try using MICE to impute missing values.

In [35]:
Project1.isnull().sum().sum()

69

The mising values:69 ar higher than the sample size:60.

In [36]:
#Removing the Refugees column to reduce missing values
#Removing non-numeric column:Regions, as it may affect MICE imputation

Project1= Project1.drop(columns=['Refugees','Regions'])

Project1.head()

,No_of_Incidents,Population,Crime_rate,Population_percentage_change,Unemployment_rate,Average_total_income,Average_value_of_dwellings,Low_income_rate,Postsecondary_Graduate,Married_or_Common_law,Non_immigrants,Non_citizen,Visible_Minority,Owner,Renter,Year
Assigned number,,,,,,,,,,,,,,,,
1,220,9413,2.337193,-3.10,11.60,34514.0,136236.00,NaN,36.86,43.98,94.60,2.44,4.10,59.66,40.34,2016
2,461,18252,2.525751,-1.03,12.48,32384.0,177993.75,0.01,42.33,56.11,92.87,5.49,1.60,85.04,14.87,2016
3,17,491,3.462322,2.10,9.40,39372.0,263604.00,0.05,58.04,47.86,76.37,22.40,3.09,49.15,50.85,2016
4,239,14584,1.638782,-0.90,11.95,43330.0,201412.00,NaN,50.37,52.14,95.70,4.08,3.05,86.51,13.49,2016
5,179,4364,4.101742,-3.50,9.70,39414.0,236826.00,NaN,49.04,37.58,85.01,9.05,9.63,46.50,53.50,2016

In [37]:
Project1.isnull().sum().sum()

41

The missing values are now less than the sample size:60. The MICE imputation will now be run.

In [38]:
#Import the required libraries

import statsmodels.imputation.mice as mice
import statsmodels.regression.linear_model as sm


#Impute the data set with MICE Data

imp = mice.MICEData(Project1)
imputed_data = imp.next_sample()

In [39]:
#n_imputations=10 as 68.33% of data is missing
#To avoid multiple random data in the dataset

mice = mice.MICE(frmla, sm.OLS, imp)
results1 = mice.fit(n_imputations=10)
print(results1.summary())

                                      Results: MICE
=========================================================================================
Method:                          MICE                   Sample size:                 60
Model:                           OLS                    Scale                        1.57
Dependent variable:              Crime_rate             Num. imputations             10
-----------------------------------------------------------------------------------------
                               Coef.   Std.Err.    t    P>|t|    [0.025    0.975]   FMI
-----------------------------------------------------------------------------------------
Intercept                    -118.4577 452.0995 -0.2620 0.7933 -1004.5565 767.6410 0.1376
Population                     -0.0000   0.0000 -1.8791 0.0602    -0.0000   0.0000 0.0307
Population_percentage_change    0.0009   0.0103  0.0915 0.9271    -0.0192   0.0211 0.1294
Unemployment_rate              -0.0374   0.0588 -0.6354 0.5252    -0.1526   0.0779 0.0253
Average_total_income            0.0000   0.0001  0.0174 0.9861    -0.0001   0.0001 0.0489
Average_value_of_dwellings     -0.0000   0.0000 -1.0719 0.2837    -0.0000   0.0000 0.1020
Low_income_rate                 3.2370   3.9126  0.8273 0.4080    -4.4315  10.9055 0.2510
Postsecondary_Graduate         -0.0433   0.0515 -0.8411 0.4003    -0.1442   0.0576 0.1154
Married_or_Common_law          -0.0491   0.0896 -0.5474 0.5841    -0.2247   0.1266 0.1098
Non_immigrants                  0.1186   0.1953  0.6072 0.5437    -0.2641   0.5013 0.1157
Non_citizen                     0.2893   0.1909  1.5151 0.1297    -0.0849   0.6635 0.1235
Visible_Minority                0.2120   0.0976  2.1731 0.0298     0.0208   0.4032 0.0585
Owner                          -0.0554   0.0371 -1.4951 0.1349    -0.1280   0.0172 0.1618
Renter                         -0.1023   0.0262 -3.9093 0.0001    -0.1536  -0.0510 0.1633
Year                            0.0600   0.2288  0.2621 0.7932    -0.3884   0.5083 0.1332
=========================================================================================

In [40]:
#Remove some variables that don't belong

frmla5 = 'Crime_rate ~ Population + Unemployment_rate + Average_total_income + ' + \
'Low_income_rate + Postsecondary_Graduate + Married_or_Common_law + Non_immigrants + ' + \
'Non_citizen + Visible_Minority + Owner + Renter'

In [41]:
#Import the required libraries

import statsmodels.imputation.mice as mice
import statsmodels.regression.linear_model as sm


#Impute the data set with MICE Data

imp = mice.MICEData(Project1)
imputed_data = imp.next_sample()

In [42]:
mice = mice.MICE(frmla5, sm.OLS, imp)
results2 = mice.fit(n_imputations=10)
print(results2.summary())

                                Results: MICE
==============================================================================
Method:                       MICE               Sample size:             60
Model:                        OLS                Scale                    1.57
Dependent variable:           Crime_rate         Num. imputations         10
------------------------------------------------------------------------------
                        Coef.  Std.Err.    t    P>|t|   [0.025   0.975]  FMI
------------------------------------------------------------------------------
Intercept              -1.9804  16.5157 -0.1199 0.9046 -34.3506 30.3898 0.3394
Population             -0.0000   0.0000 -2.5219 0.0117  -0.0000 -0.0000 0.0979
Unemployment_rate      -0.0270   0.0492 -0.5476 0.5839  -0.1234  0.0695 0.0915
Average_total_income   -0.0000   0.0001 -0.1604 0.8726  -0.0001  0.0001 0.0075
Low_income_rate         3.2863   3.0521  1.0767 0.2816  -2.6956  9.2682 0.2074
Postsecondary_Graduate -0.0527   0.0424 -1.2414 0.2145  -0.1358  0.0305 0.0672
Married_or_Common_law  -0.0389   0.0628 -0.6194 0.5356  -0.1619  0.0842 0.1757
Non_immigrants          0.1522   0.1781  0.8544 0.3929  -0.1969  0.5013 0.3494
Non_citizen             0.2353   0.2106  1.1176 0.2637  -0.1774  0.6480 0.4076
Visible_Minority        0.2037   0.1001  2.0364 0.0417   0.0076  0.3998 0.1290
Owner                  -0.0586   0.0275 -2.1298 0.0332  -0.1125 -0.0047 0.2121
Renter                 -0.0903   0.0248 -3.6343 0.0003  -0.1389 -0.0416 0.1572
==============================================================================

In [43]:
frmla6 = 'Crime_rate ~ Population + Low_income_rate + Postsecondary_Graduate + ' + \
'Non_immigrants + Non_citizen + Visible_Minority + Owner + Renter'

In [44]:
#Import the required libraries

import statsmodels.imputation.mice as mice
import statsmodels.regression.linear_model as sm


#Impute the data set with MICE Data

imp = mice.MICEData(Project1)
imputed_data = imp.next_sample()

In [45]:
mice = mice.MICE(frmla6, sm.OLS, imp)
results3 = mice.fit(n_imputations=10)
print(results3.summary())

                                Results: MICE
==============================================================================
Method:                       MICE               Sample size:             60
Model:                        OLS                Scale                    1.50
Dependent variable:           Crime_rate         Num. imputations         10
------------------------------------------------------------------------------
                        Coef.  Std.Err.    t    P>|t|   [0.025   0.975]  FMI
------------------------------------------------------------------------------
Intercept              -4.8778  13.6454 -0.3575 0.7207 -31.6223 21.8667 0.1857
Population             -0.0000   0.0000 -2.7057 0.0068  -0.0000 -0.0000 0.0280
Low_income_rate         1.6581   2.6441  0.6271 0.5306  -3.5243  6.8405 0.2041
Postsecondary_Graduate -0.0681   0.0322 -2.1159 0.0344  -0.1312 -0.0050 0.0218
Non_immigrants          0.1739   0.1430  1.2160 0.2240  -0.1064  0.4543 0.1802
Non_citizen             0.2683   0.1600  1.6767 0.0936  -0.0453  0.5820 0.1249
Visible_Minority        0.1799   0.0910  1.9783 0.0479   0.0017  0.3582 0.0842
Owner                  -0.0755   0.0122 -6.1676 0.0000  -0.0994 -0.0515 0.1408
Renter                 -0.0865   0.0214 -4.0488 0.0001  -0.1284 -0.0446 0.1287
==============================================================================

In [46]:
frmla7 = 'Crime_rate ~ Population + Low_income_rate + Postsecondary_Graduate + ' + \
'Visible_Minority + Owner + Renter'

In [47]:
#Import the required libraries

import statsmodels.imputation.mice as mice
import statsmodels.regression.linear_model as sm


#Impute the data set with MICE Data

imp = mice.MICEData(Project1)
imputed_data = imp.next_sample()

In [48]:
mice = mice.MICE(frmla7, sm.OLS, imp)
results4 = mice.fit(n_imputations=10)
print(results4.summary())

C:\Users\3939\anaconda3\lib\site-packages\statsmodels\imputation\mice.py:967: RuntimeWarning: covariance is not positive-semidefinite.
  self.params[vname] = np.random.multivariate_normal(mean=mu, cov=cov)

                                Results: MICE
=============================================================================
Method:                      MICE               Sample size:             60
Model:                       OLS                Scale                    1.54
Dependent variable:          Crime_rate         Num. imputations         10
-----------------------------------------------------------------------------
                        Coef.  Std.Err.    t    P>|t|   [0.025  0.975]  FMI
-----------------------------------------------------------------------------
Intercept              11.5267   1.1744  9.8153 0.0000  9.2250 13.8284 0.0997
Population             -0.0000   0.0000 -2.6292 0.0086 -0.0000 -0.0000 0.0176
Low_income_rate         1.9156   2.3634  0.8105 0.4176 -2.7165  6.5477 0.0947
Postsecondary_Graduate -0.0326   0.0259 -1.2622 0.2069 -0.0833  0.0180 0.0376
Visible_Minority        0.2033   0.0881  2.3080 0.0210  0.0306  0.3759 0.0269
Owner                  -0.0803   0.0107 -7.5034 0.0000 -0.1013 -0.0593 0.0358
Renter                 -0.0907   0.0191 -4.7458 0.0000 -0.1281 -0.0532 0.0319
=============================================================================

The p-value of Postsecondary_Graduate tend to increase when Non_citizen and Non_immigrants variable are removed, suggesting a multicollinearity problem. Hence, hypothesis testing will be done to check this.

In [49]:
#Final model
#Rerun the model while adding Non_immigrants and Non_citizen

frmla8 = 'Crime_rate ~ Population + Low_income_rate + ' + \
'Visible_Minority + Owner + Renter'

In [50]:
#Import the required libraries

import statsmodels.imputation.mice as mice
import statsmodels.regression.linear_model as sm


#Impute the data set with MICE Data

imp = mice.MICEData(Project1)
imputed_data = imp.next_sample()

In [51]:
mice = mice.MICE(frmla8, sm.OLS, imp)
results5 = mice.fit(n_imputations=10)
print(results5.summary())

                             Results: MICE
=======================================================================
Method:                    MICE             Sample size:           60
Model:                     OLS              Scale                  1.56
Dependent variable:        Crime_rate       Num. imputations       10
-----------------------------------------------------------------------
                  Coef.  Std.Err.    t    P>|t|   [0.025  0.975]  FMI
-----------------------------------------------------------------------
Intercept        10.8035   1.0469 10.3198 0.0000  8.7517 12.8554 0.0823
Population       -0.0000   0.0000 -2.9442 0.0032 -0.0000 -0.0000 0.0114
Low_income_rate   1.0982   2.3527  0.4668 0.6407 -3.5130  5.7093 0.0831
Visible_Minority  0.1981   0.0879  2.2533 0.0242  0.0258  0.3704 0.0204
Owner            -0.0864   0.0095 -9.1361 0.0000 -0.1049 -0.0678 0.0626
Renter           -0.0988   0.0181 -5.4544 0.0000 -0.1343 -0.0633 0.0334
=======================================================================